data_collector_url "{{cfg.data_collector_url}}"
data_collector_token "{{cfg.data_collector_token}}"
supervisor_host "{{cfg.supervisor_host}}"
habitat_ring_id "{{cfg.habitat_ring_id}}"
habitat_ring_alias "{{cfg.habitat_ring_alias}}"
