install:
	npm install

build:
	node_modules/.bin/gulp typescript

serve:
	node_modules/.bin/gulp serve

test:
	node_modules/.bin/gulp test

depclean:
	rm -rf node_modules
	npm cache clean

.PHONY: build install test depclean
