name 'build_cookbook'
maintainer 'The Prism Authors'
maintainer_email 'dev@chef.io'
license 'Apache-2.0'
version '0.1.0'

depends 'delivery-sugar'
depends 'delivery_build'
depends 'habitat-build'
depends 'delivery-truck'
