source "https://rubygems.org"

gem "rspec", :require => "spec"
gem "json"
gem "rest-client"
gem "mixlib-cli"
gem "mixlib-config"
gem "toml"
gem "chefstyle"

group :test do
  gem "json-schema"
  gem "pry"
  gem "rb-readline"
end
